import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Footer from '../components/Footer'
import styles from '../constants/style'

function Layout({ children, textOne, textTwo, textThree, titleOne, titleTwo, titleThree, img }) {
  return (
    <div className='appear bg-primary'>
    <Head>
      <title>Service Electrolux</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    
    <div className={`${styles.flexStart}`}> 
      <div className={`${styles.boxWidth}`}>
        <Hero           
          textOne={textOne}
          textTwo={textTwo}
          textThree={textThree}
          titleOne={titleOne}
          titleTwo={titleTwo}
          titleThree={titleThree}
          img={img}
        />
      </div>
    </div>

    <div className={`bg-primary ${styles.paddingX} ${styles.flexCenter}`}>
      <div className={`${styles.boxWidth}`}>
        <main>{children}</main>
        <Footer />
      </div>
    </div>
  </div>
  )
}

export default Layout